# More info: http://lonopro.com/docs/settings/
# The base config is specially treated. It gets included the other environments automatically.
# Yaml also directly supports merging with & and <<* syntax but doing it automatically
# for a cleaner syntax.
base:
  # http://lonopro.com/docs/app-scripts/
  # extract_scripts:
  #   to: "/opt"
  #   as: "ec2-user"
  # If s3_folder is set then the generated templates and app/scripts will automatically
  # be uploaded to s3.
  # There are 2 formats for s3_folder:
  # Format 1:
  # s3_folder: mybucket/path/to/folder # simple string
  # Format 2:
  # s3_folder: # Hash options in order to support multiple AWS_PROFILEs
  #   default: mybucket/path
  #   aws_profile1: mybucket/path
  #   aws_profile2: another-bucket/storage/path
  # stack_name_suffix: random # tack on a 3 char random string at the end of the stack name for lono cfn create


development:
  # The aws_profile tightly binds LONO_ENV to AWS_PROFILE and vice-versa.
  # aws_profile: dev_profile

production:
  # The aws_profile tightly binds LONO_ENV to AWS_PROFILE and vice-versa.
  # aws_profile: prod_profile
